version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
